POST http://localhost:5237/api/AccountDetails
Content-Type: application/json

{
  "Username": "User",
  "Email": "user@gmail.com",
  "Password": "12345fgdfgdgdffg",
  "CreatedAt": "2005-07-21"
}


###

GET http://localhost:5237/api/AccountDetails
###
DELETE http://localhost:5237/api/AccountDetails/2¨

###


GET http://localhost:5237/api/PasswordDetails/39
